name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: "37 4 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - registry: ghcr.io
            context: dind-keepalived
            image: dind-keepalived
          - registry: ghcr.io
            context: dnsdist
            image: dnsdist
          - registry: ghcr.io
            context: dnsdist-keepalived
            image: dnsdist-keepalived
          - registry: ghcr.io
            context: dnspython
            image: dnspython
          - registry: ghcr.io
            context: restic
            image: restic

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker QEMU
        id: qemu-raw
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      # TODO maybe drop this once https://github.com/mcflis/docker-images/pull/9 is merged
      - name: Filter Docker QEMU platforms
        id: qemu
        uses: actions/github-script@v6
        with:
          result-encoding: string
          #language=js
          script: |
            const platforms = '${{ steps.qemu-raw.outputs.platforms }}';
            console.log('derived platforms from setup-qemu-action:', platforms);
            core.setOutput('platforms', platforms.split(',').filter(p => !['linux/386', 'linux/arm/v6'].includes(p)).join(','));

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.registry }}/${{ github.repository_owner }}/${{ matrix.image }}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ghcr.io
        if: ${{ 'ghcr.io' == matrix.registry && github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          registry: ${{ matrix.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          platforms: ${{ steps.qemu.outputs.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
